service: podcast

provider:
  name: aws
  runtime: nodejs10.x

stage: dev
region: us-east-1

functions:
  podcast:
    handler: src/handler.podcast
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true
    environment:
      stage: ${self:provider.stage}
      APOLLO_API_KEY: ${ssm:APOLLO_API_KEY}

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 5000
