service: podcast

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  timeout: 60

region: us-east-1

functions:
  podcast:
    handler: src/handler.podcast
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true
    environment:
      stage: ${self:provider.stage}
      PODSERV_AWS_KEY_ID: ${ssm:PODSERV_AWS_KEY_ID}
      PODSERV_AWS_KEY_SECRET: ${ssm:PODSERV_AWS_KEY_SECRET}

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 5000
