mutation parseFeedClean($feed: String, $id: ID) {
  parse(url: $feed, id: $id) {
    name
    creator
    website
    feed
    language
    description {
      short
      long
    }
    publisher {
      name
      email
    }
    image
    episodes {
      title
      file
      date
      season
      episode
      type
      duration
    }
  }
}
