type Podcast {
  id: ID
  itunesId: ID @deprecated(reason: "Use `id`.")
  name: String
  creator: String
  website: String
  language: String
  descr: Description
  description: String @deprecated(reason: "Use `descr`.")
  publisher: Publisher
  categories: [String]
  lastBuild: String
  artworks: [Artwork]
  websub: WebSub
  colors: [Color]
  feed: String
  episodes: [Episode]
}

type Episode {
  id: ID!
  title: String
  file: String
  date: String
  descr: Description
  description: String @deprecated(reason: "Use `descr.`")
  content: String @deprecated(reason: "Use `descr`.")
  image: String
  season: String
  episode: String
  type: String
  duration: Int
  artworks: [Artwork]
}

type Description {
  short: String
  long: String
}

type Publisher {
  name: String
  email: String
}

type WebSub {
  hub: String
  url: String
}

type Color {
  name: String
  value: String
}

type Artwork {
  url: String!
  size: Int
  type: String
}

type Query {
  search(name: String!, first: Int = 20): [Podcast!]!
  podcast(itunesId: ID!): Podcast
  podcasts(itunesIds: [ID]!): [Podcast]
  episode(podcastId: ID!, episodeId: ID!): Episode
}

schema {
  query: Query
}
