type Podcast {
  itunesId: ID
  name: String
  creator: String
  slug: String
  artworks: [Artwork!]
  feed: String
  episodes: [Episode!]
  description: String
  colors: [Color]
}

type Episode {
  title: String
  file: String
  id: ID!
  description: String
  content: String
  artworks: [Artwork!]
  date: String
  duration: Int
}

type Artwork {
  url: String!
  size: Int
  type: String
}

type Color {
  name: String
  value: String
}

type Query {
  search(name: String!, first: Int = 20): [Podcast!]!
  podcast(itunesId: ID!): Podcast
  podcasts(itunesIds: [ID]!): [Podcast]
  episode(podcastId: ID!, episodeId: ID!): Episode
}

schema {
  query: Query
}
