type Podcast {
  name: String
  creator: String
  website: String
  language: String
  description: Description
  publisher: Publisher
  categories: [String]
  lastBuild: String
  image: String
  websub: WebSub
  colors: [Color]
  feed: String
  episodes: [Episode]
}

type Episode {
  title: String
  file: String
  date: String
  description: Description
  image: String
  season: String
  episode: String
  type: String
  duration: String
}

type Description {
  short: String
  long: String
}

type Publisher {
  name: String
  email: String
}

type WebSub {
  hub: String
  url: String
}

type Color {
  name: String
  value: String
}

type Query {
  search(name: String!, first: Int = 20): [Podcast!]!
  podcast(itunesId: ID!): Podcast
  podcasts(itunesIds: [ID]!): [Podcast]
  episode(podcastId: ID!, episodeId: ID!): Episode
}

schema {
  query: Query
}
